[package]
name = "mpl-bubblegum"
version = "1.4.0"
description = "Metaplex Bubblegum SDK"
authors = ["Metaplex Developers <dev@metaplex.com>"]
repository = "https://github.com/metaplex-foundation/mpl-bubblegum"
license-file = "../../LICENSE"
edition = "2021"
readme = "README.md"

[lib]
crate-type = ["cdylib", "lib"]

[features]
test-sbf = []
serde = ["dep:serde", "dep:serde_with", "kaigan/serde"]

[dependencies]
borsh = ">= 0.9, < 1.0"
kaigan = { version = ">= 0.1", features = ["serde"] }
num-derive = "^0.3"
num-traits = "^0.2"
serde = { version = "^1.0", features = ["derive"], optional = true }
serde_with = { version = "^3.0", optional = true }
solana-program = ">=1.18.11,<2"
thiserror = "^1.0.63"

[dev-dependencies]
assert_matches = "1.5.0"
bytemuck = "1.14.0"
solana-program-test = ">=1.18.11,<2"
solana-sdk = ">=1.18.11,<2"
spl-account-compression = { git = "https://github.com/StanChe/solana-program-library.git", branch = "feature/init_with_root", features = ["no-entrypoint"] }
spl-associated-token-account = { version = ">= 1.1.3", features = ["no-entrypoint"] }
spl-concurrent-merkle-tree = { git = "https://github.com/StanChe/solana-program-library.git", branch = "feature/init_with_root" }
spl-merkle-tree-reference = { git = "https://github.com/StanChe/solana-program-library.git", branch = "feature/init_with_root" }
spl-noop = { git = "https://github.com/StanChe/solana-program-library.git", branch = "feature/init_with_root", features = ["no-entrypoint"] }
spl-token = { version = ">= 3.5.0", features = ["no-entrypoint"] }
